### ISSUE TITLE
Make use of TypeScript & Reuse existing code

### ISSUE THREAD

**Issue by elertan** [AnimaAnimae/LoM-React-Client#1]
I would suggest using TypeScript over Flow because TypeScript is a more mature option, also I have a repository has a lot of stuff we can port over from that visually looks like this.

https://puu.sh/AGk1H/2ed8e1938c.png
https://puu.sh/AGk2a/16e5bb2711.png
https://puu.sh/AGk2t/c4b8fb9f72.jpg
https://puu.sh/AGk2L/c7074d77d1.jpg
https://puu.sh/AGk35/27c8f211ee.jpg

The source I have got has mostly been written to high quality standards 😄

**Comment by AnimaAnimae** [comment]
As I agree with your TypeScript suggestion... Some people that will contribute to this project have no Angular/React/... knowledge what so ever. Adding TypeScript to the pile will just be too much for now. We might give it a shot later in the project.

As for the porting stuff: We could probably re-use some code. I haven't done any visual work yet since I have no idea how it has to look like yet. Design implementation will be put on hold untill I have more information.

I'm going to close this issue and disable issues since this repo is no longer active. Please create your issues [here](https://github.com/LeagueofMemories/Client) or contact me on Discord.
